package com.ovi.tradingbeast;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 Handler h=new Handler(Looper.getMainLooper()); LinearLayout root,events; TextView status,health,cloud,balance,portfolio,plan,scanner,signal,position,performance,message,updated; boolean busy;
 int green=Color.rgb(56,232,165),white=Color.rgb(245,247,251),muted=Color.rgb(142,154,175),panel=Color.rgb(16,24,39),red=Color.rgb(255,92,112),blue=Color.rgb(85,167,255),yellow=Color.rgb(255,200,87);
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(7,11,20));getWindow().setNavigationBarColor(Color.rgb(7,11,20));ui();refresh();h.postDelayed(new Runnable(){public void run(){refresh();h.postDelayed(this,CloudConfig.POLL_MS);}},CloudConfig.POLL_MS);}
 TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setPadding(0,3,0,3);return x;}
 GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(22);return g;}
 LinearLayout card(String title){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,15,18,15);c.setBackground(bg(panel));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,7,0,7);c.setLayoutParams(p);TextView q=t(title,15,green);q.setTypeface(Typeface.DEFAULT_BOLD);q.setLetterSpacing(.05f);c.addView(q);return c;}
 void ui(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,18,16,28);root.setBackgroundColor(Color.rgb(7,11,20));s.addView(root);setContentView(s);
 TextView a=t("OVI PLUS",31,white);a.setTypeface(Typeface.create("sans-serif-black",1));a.setLetterSpacing(.1f);root.addView(a);TextView b=t("TRADING BEAST",20,green);b.setTypeface(Typeface.create("sans-serif-black",1));b.setLetterSpacing(.13f);root.addView(b);root.addView(t("CLOUD COMMAND CENTER  •  v10.0",10,muted));
 LinearLayout c=card("ACCOUNT & ENGINE");status=t("Status: CONNECTING…",16,white);health=t("Health: —",14,muted);cloud=t("Cloud: checking…",13,yellow);balance=t("Balance: —",15,white);updated=t("Last update: —",12,muted);c.addView(status);c.addView(health);c.addView(cloud);c.addView(balance);c.addView(updated);root.addView(c);
 c=card("PORTFOLIO OVERVIEW");portfolio=t("Loading portfolio…",14,white);c.addView(portfolio);root.addView(c);
 c=card("TRADING PLAN");plan=t("Entry score ≥ 55\nBuyer strength ≥ 70%\nOne entry per project • No re-entry\nPaper trading • No wallet signing/broadcast",14,white);c.addView(plan);root.addView(c);
 c=card("SCANNER INTELLIGENCE");scanner=t("Waiting for cloud scanner…",14,white);c.addView(scanner);root.addView(c);
 c=card("LATEST SIGNAL");signal=t("No signal yet.",14,white);c.addView(signal);root.addView(c);
 c=card("ACTIVE POSITIONS");position=t("No active position.",14,muted);c.addView(position);root.addView(c);
 c=card("PERFORMANCE");performance=t("Entries: —\nTake profits: —\nRejected: —",14,white);c.addView(performance);root.addView(c);
 c=card("LIVE ACTIVITY");c.addView(t("● LIVE FEED  •  CLOUD CONNECTED  •  10s REFRESH  •  newest first",12,green));events=new LinearLayout(this);events.setOrientation(LinearLayout.VERTICAL);c.addView(events);root.addView(c);
 message=t("SYSTEM READY  •  PAPER MODE  •  NO WALLET SIGNING",13,muted);root.addView(message);c=card("BOT CONTROLS");c.addView(btn("START BOT",green,"start"));c.addView(btn("STOP BOT",yellow,"stop"));c.addView(btn("RESUME BOT",blue,"resume"));c.addView(btn("EMERGENCY STOP",red,"emergency-stop"));c.addView(btn("SCAN NOW",white,"scan"));root.addView(c);}
 Button btn(String s,int col,final String act){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(7,11,20));b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(bg(col));b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){control(act);}});b.setLayoutParams(new LinearLayout.LayoutParams(-1,52));return b;}
 void refresh(){if(busy)return;busy=true;new Thread(new Runnable(){public void run(){final String r=get("/status");runOnUiThread(new Runnable(){public void run(){busy=false;if(r==null){cloud.setText("Cloud: OFFLINE / retrying…");cloud.setTextColor(red);return;}cloud.setText("Cloud: ONLINE");cloud.setTextColor(green);try{parse(new JSONObject(r));}catch(Exception e){message.setText("Cloud response could not be read.");}}});}}).start();loadEvents();}
 void parse(JSONObject o)throws Exception{JSONObject s=o.optJSONObject("state");if(s==null)s=o;status.setText("Status: "+s.optString("status","UNKNOWN"));health.setText("Health: "+s.optString("health","—"));JSONObject set=o.optJSONObject("settings");if(set!=null)plan.setText("Entry score ≥ 55\nBuyer strength ≥ 70%\nOne entry per project • No re-entry\nTrade amount: "+set.optString("trade_amount","—")+"\nMode: "+set.optString("mode","PAPER")+"\nPaper trading • No wallet signing/broadcast");JSONObject st=s.optJSONObject("stats");if(st!=null)performance.setText("Entries: "+st.optInt("entries",0)+"\nTake profits: "+st.optInt("take_profits",0)+"\nRejected: "+st.optInt("rejected",0));JSONObject sg=s.optJSONObject("latest_signal");signal.setText(sg==null?"No signal yet.":"Candidate: "+sg.optString("symbol",sg.optString("token","—"))+"\nScore: "+sg.optString("score","—")+" / 100\nBuyer strength: "+sg.optString("buy_ratio",sg.optString("buyer_pressure","—"))+"\nPrice: "+sg.optString("price_usd","—")+"\nLevel: "+sg.optString("opportunity_level","—"));JSONArray ps=s.optJSONArray("positions");if(ps==null||ps.length()==0)position.setText("No active position.");else{StringBuilder z=new StringBuilder();for(int i=0;i<ps.length();i++){JSONObject p=ps.optJSONObject(i);if(p!=null)z.append("LIVE POSITION\n").append(p.optString("symbol",p.optString("token","—"))).append("\nEntry: ").append(p.optString("entry_price","—")).append("   Target: ").append(p.optString("target_price",p.optString("tp","—"))).append("\nP/L: ").append(p.optString("pnl_pct",p.optString("pnl","—"))).append("\n\n");}position.setText(z.toString().trim());}JSONObject pf=s.optJSONObject("portfolio");portfolio.setText(pf==null?"Portfolio data will appear when supplied by the cloud engine.":"Bankroll: "+pf.optString("bankroll",pf.optString("balance","—"))+"\nDeployed: "+pf.optString("deployed","—")+"\nAvailable: "+pf.optString("available","—"));scanner.setText("Threshold gate: SCORE ≥ 55  •  BUYERS ≥ 70%\nCloud scanner state is shown above when available.");updated.setText("Last update: "+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date()));}
 void loadEvents(){new Thread(new Runnable(){public void run(){final String r=get("/events");if(r==null)return;runOnUiThread(new Runnable(){public void run(){try{JSONObject o=new JSONObject(r);JSONArray a=o.optJSONArray("events");events.removeAllViews();if(a==null||a.length()==0){TextView wait=t("LIVE FEED IS READY\nWaiting for the next bot event…",13,muted);wait.setPadding(12,14,12,14);events.addView(wait);return;}int start=Math.max(0,a.length()-18);for(int i=a.length()-1;i>=start;i--){JSONObject e=a.optJSONObject(i);if(e==null)continue;String kind=e.optString("kind","EVENT");
TextView row=t("●  "+kind+"\\n"+e.optString("message",e.toString())+"\\n"+e.optString("timestamp",e.optString("time","")),14,white);
row.setPadding(14,11,14,11);
GradientDrawable rb=bg(Color.rgb(22,32,50));
row.setBackground(rb);
LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);
rp.setMargins(0,3,0,3);
row.setLayoutParams(rp);
events.addView(row);}}catch(Exception ignored){}}});}}).start();}
 void control(final String a){message.setText("Sending "+a+" command…");new Thread(new Runnable(){public void run(){final boolean ok=get("/control/"+a)!=null;runOnUiThread(new Runnable(){public void run(){message.setText(ok?"Command sent: "+a:"Command failed: "+a);if(ok)refresh();}});}}).start();}
 String get(String path){HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(CloudConfig.BASE_URL+path).openConnection();c.setRequestMethod("GET");c.setConnectTimeout(12000);c.setReadTimeout(15000);int code=c.getResponseCode();InputStream in=code>=200&&code<400?c.getInputStream():c.getErrorStream();if(in==null)return null;BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);r.close();return code>=200&&code<400?s.toString():null;}catch(Exception e){return null;}finally{if(c!=null)c.disconnect();}}
 protected void onDestroy(){super.onDestroy();h.removeCallbacksAndMessages(null);}
}
