plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ovi.tradingbeast'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ovi.tradingbeast'
        minSdk 23
        targetSdk 35
        versionCode 10
        versionName '10.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }
}
